import { PresentationData } from '../types';

export const SAMPLE_PRESENTATIONS: PresentationData[] = [
  {
    id: 'demo-tech-ai',
    title: 'El Futuro de la Inteligencia Artificial 2026',
    totalDuration: 25.5,
    slides: [
      {
        id: 's1',
        index: 0,
        title: 'El Futuro de la Inteligencia Artificial',
        subtitle: 'Transformación autónoma y creatividad sin límites',
        duration: 6.5,
        backgroundColor: '#090d16',
        backgroundImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
        narrationScript: 'Bienvenidos a la nueva era digital: cómo la inteligencia artificial está revolucionando nuestra forma de crear, trabajar y comunicarnos.',
        directorCue: {
          cameraMove: 'ken-burns-zoom',
          pacingTone: 'cinematic',
          transitionOut: 'zoom-through',
          accentColor: '#38bdf8',
          keyHighlightWords: ['Futuro', 'Inteligencia Artificial', 'Transformación'],
        },
        elements: [
          {
            id: 'e1-bg',
            type: 'IMAGE',
            imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
            position: { x: 5, y: 15, width: 90, height: 75, zIndex: 1 },
            animation: {
              delay: 0,
              duration: 8,
              effect: 'ken-burns',
              zoomDirection: 'zoom-in-center',
              scaleRange: [1.02, 1.25],
            },
          },
          {
            id: 'e1-title',
            type: 'TITLE',
            content: 'El Futuro de la IA',
            position: { x: 10, y: 30, width: 80, height: 20, zIndex: 10 },
            style: { fontSize: 44, fontWeight: 800, color: '#ffffff', textAlign: 'center' },
            animation: { delay: 0.4, duration: 1.2, effect: 'spring-reveal' },
          },
          {
            id: 'e1-sub',
            type: 'SUBTITLE',
            content: 'De diapositivas estáticas a videos dinámicos completamente automáticos',
            position: { x: 15, y: 55, width: 70, height: 18, zIndex: 10 },
            style: { fontSize: 20, fontWeight: 500, color: '#93c5fd', textAlign: 'center' },
            animation: { delay: 1.0, duration: 1.0, effect: 'fade-up' },
          },
        ],
      },
      {
        id: 's2',
        index: 1,
        title: 'Animación Autónoma de Imágenes',
        subtitle: 'Efecto Ken Burns y profundidad cinematográfica',
        duration: 6.8,
        backgroundColor: '#0b1329',
        narrationScript: 'Cada imagen de la diapositiva cobra vida automáticamente con paneos suaves y enfoques visuales de alta precisión sin necesidad de configuración manual.',
        directorCue: {
          cameraMove: 'pan-horizontal',
          pacingTone: 'dynamic',
          transitionOut: 'slide-left',
          accentColor: '#818cf8',
          keyHighlightWords: ['Autónoma', 'Ken Burns', 'Profundidad'],
        },
        elements: [
          {
            id: 'e2-img1',
            type: 'IMAGE',
            imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
            position: { x: 50, y: 15, width: 45, height: 70, zIndex: 5 },
            animation: {
              delay: 0.2,
              duration: 8,
              effect: 'ken-burns',
              zoomDirection: 'pan-left-to-right',
              scaleRange: [1.05, 1.22],
            },
          },
          {
            id: 'e2-title',
            type: 'TITLE',
            content: 'Movimiento Orgánico',
            position: { x: 8, y: 22, width: 38, height: 18, zIndex: 10 },
            style: { fontSize: 32, fontWeight: 700, color: '#f8fafc', textAlign: 'left' },
            animation: { delay: 0.3, duration: 1, effect: 'spring-reveal' },
          },
          {
            id: 'e2-b1',
            type: 'BODY',
            content: '• Trayectorias de cámara inteligentes según el encuadre.',
            position: { x: 8, y: 44, width: 38, height: 14, zIndex: 10 },
            style: { fontSize: 16, color: '#cbd5e1', textAlign: 'left' },
            animation: { delay: 0.8, duration: 0.8, effect: 'fade-up' },
          },
          {
            id: 'e2-b2',
            type: 'BODY',
            content: '• Profundidad multicapa y sincronización de velocidad.',
            position: { x: 8, y: 60, width: 38, height: 14, zIndex: 10 },
            style: { fontSize: 16, color: '#cbd5e1', textAlign: 'left' },
            animation: { delay: 1.4, duration: 0.8, effect: 'fade-up' },
          },
        ],
      },
      {
        id: 's3',
        index: 2,
        title: 'Tipografía Cinética Inteligente',
        subtitle: 'Entradas escalonadas al ritmo natural de lectura',
        duration: 6.2,
        backgroundColor: '#111827',
        narrationScript: 'Los títulos, subtítulos y listas de puntos aparecen con tipografía cinética escalonada para mantener la atención constante del espectador.',
        directorCue: {
          cameraMove: 'subtle-pulse',
          pacingTone: 'cinematic',
          transitionOut: 'blur-dissolve',
          accentColor: '#34d399',
          keyHighlightWords: ['Tipografía', 'Ritmo', 'Atención'],
        },
        elements: [
          {
            id: 'e3-img',
            type: 'IMAGE',
            imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
            position: { x: 6, y: 20, width: 42, height: 62, zIndex: 5 },
            animation: {
              delay: 0.2,
              duration: 7,
              effect: 'ken-burns',
              zoomDirection: 'zoom-out-center',
              scaleRange: [1.18, 1.02],
            },
          },
          {
            id: 'e3-title',
            type: 'TITLE',
            content: 'Lectura Dinámica',
            position: { x: 52, y: 20, width: 44, height: 16, zIndex: 10 },
            style: { fontSize: 32, fontWeight: 700, color: '#ffffff', textAlign: 'left' },
            animation: { delay: 0.4, duration: 1, effect: 'spring-reveal' },
          },
          {
            id: 'e3-b1',
            type: 'BODY',
            content: '✨ Detección automática de jerarquía y palabras clave.',
            position: { x: 52, y: 40, width: 44, height: 12, zIndex: 10 },
            style: { fontSize: 16, color: '#e2e8f0', textAlign: 'left' },
            animation: { delay: 0.9, duration: 0.8, effect: 'fade-up' },
          },
          {
            id: 'e3-b2',
            type: 'BODY',
            content: '⚡ Pacing automático ajustado al volumen de lectura.',
            position: { x: 52, y: 55, width: 44, height: 12, zIndex: 10 },
            style: { fontSize: 16, color: '#e2e8f0', textAlign: 'left' },
            animation: { delay: 1.5, duration: 0.8, effect: 'fade-up' },
          },
          {
            id: 'e3-b3',
            type: 'BODY',
            content: '🎵 Sincronización con música de fondo procedural.',
            position: { x: 52, y: 70, width: 44, height: 12, zIndex: 10 },
            style: { fontSize: 16, color: '#e2e8f0', textAlign: 'left' },
            animation: { delay: 2.1, duration: 0.8, effect: 'fade-up' },
          },
        ],
      },
      {
        id: 's4',
        index: 3,
        title: 'Exportación a Video HD con 1 Clic',
        subtitle: 'Listo para compartir en redes o presentaciones de alto impacto',
        duration: 6.0,
        backgroundColor: '#0f172a',
        narrationScript: 'Convierte tus ideas en videos listos para compartir con exportación instantánea en alta resolución.',
        directorCue: {
          cameraMove: 'ken-burns-zoom',
          pacingTone: 'dynamic',
          transitionOut: 'crossfade',
          accentColor: '#f43f5e',
          keyHighlightWords: ['Exportación', 'Video HD', '1 Clic'],
        },
        elements: [
          {
            id: 'e4-img',
            type: 'IMAGE',
            imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
            position: { x: 10, y: 15, width: 80, height: 70, zIndex: 1 },
            animation: {
              delay: 0,
              duration: 8,
              effect: 'ken-burns',
              zoomDirection: 'zoom-in-center',
              scaleRange: [1.03, 1.2],
            },
          },
          {
            id: 'e4-title',
            type: 'TITLE',
            content: '¡Crea tu Video Automático Ahora!',
            position: { x: 10, y: 35, width: 80, height: 18, zIndex: 10 },
            style: { fontSize: 38, fontWeight: 800, color: '#ffffff', textAlign: 'center' },
            animation: { delay: 0.4, duration: 1.2, effect: 'spring-reveal' },
          },
          {
            id: 'e4-sub',
            type: 'SUBTITLE',
            content: 'Conecta tu Google Drive o pega el enlace de tu Google Slides',
            position: { x: 15, y: 56, width: 70, height: 16, zIndex: 10 },
            style: { fontSize: 18, fontWeight: 500, color: '#fbcfe8', textAlign: 'center' },
            animation: { delay: 1.0, duration: 1.0, effect: 'fade-up' },
          },
        ],
      },
    ],
  },
  {
    id: 'demo-startup-pitch',
    title: 'Estrategia de Crecimiento y Pitch 2026',
    totalDuration: 21.0,
    slides: [
      {
        id: 'pitch-s1',
        index: 0,
        title: 'Revolucionando el Contenido en Video',
        subtitle: 'Automatización total desde presentaciones existentes',
        duration: 7.0,
        backgroundColor: '#091522',
        narrationScript: 'Las presentaciones tradicionales son estáticas y aburridas. Nuestra plataforma las convierte en piezas audiovisuales de alto engagement al instante.',
        directorCue: {
          cameraMove: 'ken-burns-zoom',
          pacingTone: 'dynamic',
          transitionOut: 'zoom-through',
          accentColor: '#38bdf8',
          keyHighlightWords: ['Revolucionando', 'Video', 'Automatización'],
        },
        elements: [
          {
            id: 'p1-img',
            type: 'IMAGE',
            imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1000&q=80',
            position: { x: 50, y: 15, width: 45, height: 70, zIndex: 2 },
            animation: {
              delay: 0.1,
              duration: 8,
              effect: 'ken-burns',
              zoomDirection: 'zoom-in-center',
              scaleRange: [1.02, 1.22],
            },
          },
          {
            id: 'p1-title',
            type: 'TITLE',
            content: 'Zero-Effort Video',
            position: { x: 6, y: 25, width: 40, height: 18, zIndex: 10 },
            style: { fontSize: 36, fontWeight: 800, color: '#ffffff', textAlign: 'left' },
            animation: { delay: 0.3, duration: 1, effect: 'spring-reveal' },
          },
          {
            id: 'p1-b1',
            type: 'BODY',
            content: 'Transforma cualquier presentación de Google Drive en un video dinámico sin tocar una línea de tiempo manual.',
            position: { x: 6, y: 48, width: 40, height: 28, zIndex: 10 },
            style: { fontSize: 18, color: '#94a3b8', textAlign: 'left' },
            animation: { delay: 0.9, duration: 1, effect: 'fade-up' },
          },
        ],
      },
      {
        id: 'pitch-s2',
        index: 1,
        title: 'Métricas de Impacto',
        subtitle: 'Mayor retención y velocidad de producción',
        duration: 7.0,
        backgroundColor: '#0c1b18',
        narrationScript: 'El video genera 3 veces más retención que un PDF o pase de diapositivas convencional, multiplicando el alcance de tu mensaje.',
        directorCue: {
          cameraMove: 'pan-horizontal',
          pacingTone: 'corporate',
          transitionOut: 'slide-left',
          accentColor: '#10b981',
          keyHighlightWords: ['Métricas', 'Impacto', 'Retención'],
        },
        elements: [
          {
            id: 'p2-img',
            type: 'IMAGE',
            imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1000&q=80',
            position: { x: 5, y: 15, width: 45, height: 70, zIndex: 2 },
            animation: {
              delay: 0.1,
              duration: 8,
              effect: 'ken-burns',
              zoomDirection: 'pan-left-to-right',
              scaleRange: [1.04, 1.2],
            },
          },
          {
            id: 'p2-title',
            type: 'TITLE',
            content: '3x Mayor Retención',
            position: { x: 54, y: 22, width: 42, height: 16, zIndex: 10 },
            style: { fontSize: 34, fontWeight: 800, color: '#34d399', textAlign: 'left' },
            animation: { delay: 0.4, duration: 1, effect: 'spring-reveal' },
          },
          {
            id: 'p2-b1',
            type: 'BODY',
            content: '📈 85% de ahorro de tiempo frente a herramientas de edición manual.',
            position: { x: 54, y: 44, width: 42, height: 14, zIndex: 10 },
            style: { fontSize: 16, color: '#e2e8f0', textAlign: 'left' },
            animation: { delay: 1.0, duration: 0.8, effect: 'fade-up' },
          },
          {
            id: 'p2-b2',
            type: 'BODY',
            content: '🎯 Animaciones fluidas generadas por IA y física cinematográfica.',
            position: { x: 54, y: 62, width: 42, height: 14, zIndex: 10 },
            style: { fontSize: 16, color: '#e2e8f0', textAlign: 'left' },
            animation: { delay: 1.6, duration: 0.8, effect: 'fade-up' },
          },
        ],
      },
      {
        id: 'pitch-s3',
        index: 2,
        title: 'El Próximo Paso',
        subtitle: 'Empieza a generar tus videos hoy',
        duration: 7.0,
        backgroundColor: '#18122b',
        narrationScript: 'Conecta tu cuenta de Google y dale vida a tus diapositivas con un solo clic.',
        directorCue: {
          cameraMove: 'ken-burns-zoom',
          pacingTone: 'cinematic',
          transitionOut: 'crossfade',
          accentColor: '#c084fc',
          keyHighlightWords: ['Próximo', 'Paso', 'Hoy'],
        },
        elements: [
          {
            id: 'p3-img',
            type: 'IMAGE',
            imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1000&q=80',
            position: { x: 10, y: 15, width: 80, height: 70, zIndex: 1 },
            animation: {
              delay: 0,
              duration: 8,
              effect: 'ken-burns',
              zoomDirection: 'zoom-in-center',
              scaleRange: [1.03, 1.25],
            },
          },
          {
            id: 'p3-title',
            type: 'TITLE',
            content: 'Transforma tus Slides en Video',
            position: { x: 10, y: 35, width: 80, height: 20, zIndex: 10 },
            style: { fontSize: 40, fontWeight: 800, color: '#ffffff', textAlign: 'center' },
            animation: { delay: 0.4, duration: 1.2, effect: 'spring-reveal' },
          },
          {
            id: 'p3-sub',
            type: 'SUBTITLE',
            content: 'Rápido, 100% automático y profesional',
            position: { x: 15, y: 58, width: 70, height: 16, zIndex: 10 },
            style: { fontSize: 20, fontWeight: 600, color: '#e9d5ff', textAlign: 'center' },
            animation: { delay: 1.0, duration: 1.0, effect: 'fade-up' },
          },
        ],
      },
    ],
  },
];
